### ISSUE TITLE
Add support to OpenClover

### ISSUE THREAD

**Issue by ljmf00** [codacy/coverage-parser#33] opened 2019-08-26 12:38 UTC
Documentation: http://openclover.org/doc/manual/latest/ant--clover-report.html

**Comment by ljmf00** [comment] 2019-10-14 18:15
I marked this as `Low Priority` because there is already a coverage tool

**Comment by lolgab** [comment] 2019-11-06 13:49
I'm closing it as duplicate of #32

**Closed by lolgab** 2019-11-06 13:49 UTC
Labels: Low Priority
