### ISSUE TITLE
Getting a divide by zero error parsing my jacoco file.

### ISSUE THREAD

**Issue by mi3e** [codacy/coverage-parser#26] opened 2019-02-15 21:20 UTC
Any help much appreciated, better code coverage reporting equals a sweeter smelling garden

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:34 min
[INFO] Finished at: 2019-02-15T21:17:24+00:00
[INFO] Final Memory: 89M/1143M
[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal com.gavinmogan:codacy-maven-plugin:1.0.3:coverage (post-test) on project backend: Execution post-test of goal com.gavinmogan:codacy-maven-plugin:1.0.3:coverage failed: / by zero -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.gavinmogan:codacy-maven-plugin:1.0.3:coverage (post-test) on project backend: Execution post-test of goal com.gavinmogan:codacy-maven-plugin:1.0.3:coverage failed: / by zero
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution post-test of goal com.gavinmogan:codacy-maven-plugin:1.0.3:coverage failed: / by zero
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.ArithmeticException: / by zero
	at com.codacy.parsers.implementation.JacocoParser.com$codacy$parsers$implementation$JacocoParser$$lineCoverage(JacocoParser.scala:47)
	at com.codacy.parsers.implementation.JacocoParser$$anonfun$5$$anonfun$apply$1.apply(JacocoParser.scala:32)
	at com.codacy.parsers.implementation.JacocoParser$$anonfun$5$$anonfun$apply$1.apply(JacocoParser.scala:30)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.codacy.parsers.implementation.JacocoParser$$anonfun$5.apply(JacocoParser.scala:29)
	at com.codacy.parsers.implementation.JacocoParser$$anonfun$5.apply(JacocoParser.scala:27)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at com.codacy.parsers.implementation.JacocoParser.generateReport(JacocoParser.scala:26)
	at com.gavinmogan.CodacyCoverageReporterMojo.processReport(CodacyCoverageReporterMojo.java:196)
	at com.gavinmogan.CodacyCoverageReporterMojo.execute(CodacyCoverageReporterMojo.java:121)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more

Some snippets from the pom.xml I'm using

```

<groupId>org.jacoco</groupId>
<artifactId>jacoco-maven-plugin</artifactId>
<version>0.8.3</version>
```

And using the supported codacy maven plugin

```
<plugin>
	<groupId>com.gavinmogan</groupId>
	<artifactId>codacy-maven-plugin</artifactId>
	<version>1.0.3</version>
	<configuration>
		<apiToken>${codacy.api.key}</apiToken>
		<projectToken>${codacy.project.key}</projectToken>
		<coverageReportFile>${project.build.directory}/site/jacoco/jacoco.xml</coverageReportFile>
		<!--<commit>${env.TRAVIS_COMMIT}</commit>-->
		<codacyApiBaseUrl>https://api.codacy.com</codacyApiBaseUrl>
		<failOnMissingReportFile>true</failOnMissingReportFile>
	</configuration>
	<executions>
		<execution>
			<id>post-test</id>
			<phase>post-integration-test</phase>
			<goals>
				<goal>coverage</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

See attached jacoco.xml file that causes the fail.

[jacoco.txt](https://github.com/codacy/coverage-parser/files/2870899/jacoco.txt)

**Comment by IGFCoimbra** [comment] 2019-05-29 10:36
Hi @mi3e 

I'm very sorry for the delay in getting back to you. 

If you are still having this issue, please reach out to support@codacy.com so one of our engineers can help you with this. 

Regards,
Ivo

**Comment by ljmf00** [comment] 2019-08-28 10:51
Duplicate of #35

**Closed by ljmf00** 2019-08-28 10:51 UTC
